module.exports = {
    kind: 'youtube#playlistItemListResponse',
    etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/HfhWmLlsAQt0hf-ibFM1zJ7P0Z8"',
    nextPageToken: 'CDIQAA',
    pageInfo: {totalResults: 65, resultsPerPage: 50},
    items: [{
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/tLTeuvBy6QYO-EsAnlIuOm8-uKg"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuOTRFRDhFMjIwMjlDM0I1Rg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Symphony No. 4 in F minor, Op. 36: II. Andantino in modo di canzone',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nSymphony No. 4 in F minor, Op. 36: II. Andantino in modo di canzone · Pyotr Ilyich Tchaikovsky · Royal Philharmonic Orchestra · Artur Rodzinski · Erika Morini\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/KYfkFB0IktQ/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/KYfkFB0IktQ/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/KYfkFB0IktQ/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/KYfkFB0IktQ/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/KYfkFB0IktQ/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 0,
            resourceId: {kind: 'youtube#video', videoId: 'KYfkFB0IktQ'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/579E4jfgnyupRiXKHaBe5ZIPPB8"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQjU2NjdFQjVDMjY5RTdFOQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Stars and Stripes Forever',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nStars and Stripes Forever · Various Artists · John Philip Sousa · Concertgebouw Orchestra · Eduard van Beinum\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/43i4UvNHgoM/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/43i4UvNHgoM/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/43i4UvNHgoM/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/43i4UvNHgoM/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/43i4UvNHgoM/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 1,
            resourceId: {kind: 'youtube#video', videoId: '43i4UvNHgoM'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/cdQ6NFApyuqNc6m-spYlZc-cN2c"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQ0JDOTMwM0NEMzVCQTA5QQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Lakmé: Act I, The Flower Duet',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nLakmé: Act I, The Flower Duet · Léo Delibes · Ché & Charlie\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/V0pakGAv6Uo/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/V0pakGAv6Uo/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/V0pakGAv6Uo/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/V0pakGAv6Uo/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/V0pakGAv6Uo/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 2,
            resourceId: {kind: 'youtube#video', videoId: 'V0pakGAv6Uo'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/swsUR4fG-62Z2Q2apD_rpCa4fGo"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQTA3Mjk5ODVCMDY5M0ZGOA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Finlandia, Op. 26',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nFinlandia, Op. 26 · Various Artists · Jean Sibelius · The London Philharmonic Orchestra · Sir Adrian Boult\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/ttSfHy9BI8w/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/ttSfHy9BI8w/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/ttSfHy9BI8w/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/ttSfHy9BI8w/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/ttSfHy9BI8w/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 3,
            resourceId: {kind: 'youtube#video', videoId: 'ttSfHy9BI8w'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/S8GJfM96uOJEi-WWf8spuxL7I1A"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNzJBNEU0MjVEOUU5NTU4NA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Peer Gynt - Suite No. 1, Op. 46: I. Morning Mood',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPeer Gynt - Suite No. 1, Op. 46: I. Morning Mood · Various Artists · Edvard Grieg · Moscow Radio Orchestra · Nikolai Golovanov\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/0rgDg96pGn0/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/0rgDg96pGn0/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/0rgDg96pGn0/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/0rgDg96pGn0/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/0rgDg96pGn0/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 4,
            resourceId: {kind: 'youtube#video', videoId: '0rgDg96pGn0'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/-NJwvg7IzMqyGp5Oc_W5IMyFjsM"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMjJDRTI1QTcxQ0E2QTNBOA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'The Lark Ascending',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nThe Lark Ascending · Ralph Vaughan Williams · London Philharmonic Orchestra · Sir Adrian Boult · Jean Pougnet\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/TA5EfjamTUA/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/TA5EfjamTUA/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/TA5EfjamTUA/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/TA5EfjamTUA/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/TA5EfjamTUA/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 5,
            resourceId: {kind: 'youtube#video', videoId: 'TA5EfjamTUA'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/OIXqZhNiZmiiAqBbTXo1Ss1EcTU"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuM0JBRUQ0NURFQkI4MDNFMQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Brandenburg Concerto No.3 in G Major, BWV 1048',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nBrandenburg Concerto No.3 in G Major, BWV 1048 · Johann Sebastian Bach · Bath Festival Chamber Orchestra · Robert Masters · Yehudi Menuhin\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/8U_cm5sMxyA/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/8U_cm5sMxyA/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/8U_cm5sMxyA/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/8U_cm5sMxyA/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/8U_cm5sMxyA/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 6,
            resourceId: {kind: 'youtube#video', videoId: '8U_cm5sMxyA'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/R_miNouqIB5YPonFYVW_JRyQaz8"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMDFDNzlDRkQ0REVFMEM3Qg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Pie Jesu',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPie Jesu · Andrew Lloyd Webber · Ché & Charlie\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: EMI MILLS MUSIC\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/D17TEgTwc6c/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/D17TEgTwc6c/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/D17TEgTwc6c/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/D17TEgTwc6c/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/D17TEgTwc6c/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 7,
            resourceId: {kind: 'youtube#video', videoId: 'D17TEgTwc6c'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/Heo9wxzZItB8kklvSb1oRRGy820"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuRDk1QzFFMURFNUFBNUYxOA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Gaspard de la nuit: I. Ondine',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nGaspard de la nuit: I. Ondine · Maurice Ravel · Cor de Groot\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Boosey & Hawkes\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/c0y8JfJsK8o/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/c0y8JfJsK8o/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/c0y8JfJsK8o/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/c0y8JfJsK8o/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/c0y8JfJsK8o/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 8,
            resourceId: {kind: 'youtube#video', videoId: 'c0y8JfJsK8o'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/xszksGBV01nW-I6pQi9D1TKMZBQ"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQjNENUEzNjI3NDcwRjA4MA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'La Valse',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nLa Valse · Various Artists · Maurice Ravel · Concertgebouw Orchestra · Eduard van Beinum\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/NQGY1VBpSmo/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/NQGY1VBpSmo/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/NQGY1VBpSmo/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/NQGY1VBpSmo/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/NQGY1VBpSmo/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 9,
            resourceId: {kind: 'youtube#video', videoId: 'NQGY1VBpSmo'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/zNFE-n3AE212VoMKYwuvmMPAIcM"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuRTBCMzk2NTFEREUwNUUzMQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: "Piano Sonata No. 14 in C Sharp Minor, Op. 27, No. 2, 'Moonlight Sonata': I. Adagio Sostenuto",
            description: "Provided to YouTube by The Orchard Enterprises\n\nPiano Sonata No. 14 in C Sharp Minor, Op. 27, No. 2, 'Moonlight Sonata': I. Adagio Sostenuto · Ludwig van Beethoven · David Moore\n\nClassical Music Playlist\n\n℗ 2012 In The Mood\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.",
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/5H2Fz-yaLqs/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/5H2Fz-yaLqs/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/5H2Fz-yaLqs/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/5H2Fz-yaLqs/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/5H2Fz-yaLqs/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 10,
            resourceId: {kind: 'youtube#video', videoId: '5H2Fz-yaLqs'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/6KD1GhqXPYeBUl1ChOi-d9NlQ_M"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMTBFRDNGNEFCNjdCRDk2OQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: "Serenade in G major, 'Eine kleine Nachtmusik', K. 525,: IV. Rondo Allegro",
            description: "Provided to YouTube by The Orchard Enterprises\n\nSerenade in G major, 'Eine kleine Nachtmusik', K. 525,: IV. Rondo Allegro · Various Artists · Wolfgang Amadeus Mozart · Berlin Philharmonic Orchestra · Herbert von Karajan\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: THE REALLY USEFUL GROUP LTD\n\nAuto-generated by YouTube.",
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/uKbDK4jqUjQ/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/uKbDK4jqUjQ/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/uKbDK4jqUjQ/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/uKbDK4jqUjQ/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/uKbDK4jqUjQ/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 11,
            resourceId: {kind: 'youtube#video', videoId: 'uKbDK4jqUjQ'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/PQsQzyBCOc8bApOppbI2CphtWwQ"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNTgzMDE2OUZCQkQwQ0Q1Mg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Elizabethan Serenade',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nElizabethan Serenade · Various Artists · Ronald Binge · David Moore Ensemble\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/aUxeE56k7XI/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/aUxeE56k7XI/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/aUxeE56k7XI/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/aUxeE56k7XI/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/aUxeE56k7XI/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 12,
            resourceId: {kind: 'youtube#video', videoId: 'aUxeE56k7XI'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/rJZuHwS2u-FXz8kD9-NqhBM-oAc"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuN0FGNjY4RDlBQzAxODI4MQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Pavane pour une infante défunte',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPavane pour une infante défunte · Maurice Ravel · Robert Casadesus\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/d-rJmeTA9kM/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/d-rJmeTA9kM/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/d-rJmeTA9kM/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/d-rJmeTA9kM/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/d-rJmeTA9kM/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 13,
            resourceId: {kind: 'youtube#video', videoId: 'd-rJmeTA9kM'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/whW1m8WabP-zcppDMSPhnKq_JB4"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNkRDODE3MkQ5OUZBRjA4OQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Pavane, Op. 50',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPavane, Op. 50 · Various Artists · Gabriel Fauré · French National Radio Orchestra · Sir Thomas Beecham\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/RV_uPAwO5Po/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/RV_uPAwO5Po/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/RV_uPAwO5Po/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/RV_uPAwO5Po/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/RV_uPAwO5Po/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 14,
            resourceId: {kind: 'youtube#video', videoId: 'RV_uPAwO5Po'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/dLr084U051sJJWI0BG8h3rrULJc"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMjgzN0EzMjJBRUQ3RDMzRA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Preludes, Book I: VIII. La fille aux cheveux de lin (The Girl with the Flaxen Hair)',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPreludes, Book I: VIII. La fille aux cheveux de lin (The Girl with the Flaxen Hair) · Claude Debussy · David Moore\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/gdjnGOpRhJQ/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/gdjnGOpRhJQ/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/gdjnGOpRhJQ/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/gdjnGOpRhJQ/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/gdjnGOpRhJQ/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 15,
            resourceId: {kind: 'youtube#video', videoId: 'gdjnGOpRhJQ'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/kMHfNtZ0yFYM-BrTkC9MwW-tu98"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQzAwNUE1NzYxRDhCRDUzQw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Spartacus Suite No. 1: I. Adagio of Spartacus and Phrygia',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nSpartacus Suite No. 1: I. Adagio of Spartacus and Phrygia · Various Artists · Aram Khachaturian · Vienna Philharmonic Orchestra\n\nClassical Music Playlist\n\n℗ 2013 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/uqlSwBztyhk/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/uqlSwBztyhk/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/uqlSwBztyhk/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/uqlSwBztyhk/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/uqlSwBztyhk/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 16,
            resourceId: {kind: 'youtube#video', videoId: 'uqlSwBztyhk'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/JEI1dEpd40cHR1mID5giM8JVZ5I"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNjc4MkJBRTRFMjk2QzJBOA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Peer Gynt - Suite No. 1, Op. 46: II. The Death of Aase',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPeer Gynt - Suite No. 1, Op. 46: II. The Death of Aase · Various Artists · Edvard Grieg · Moscow Radio Orchestra · Nikolai Golovanov\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/xS6B1l9V17I/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/xS6B1l9V17I/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/xS6B1l9V17I/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/xS6B1l9V17I/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/xS6B1l9V17I/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 17,
            resourceId: {kind: 'youtube#video', videoId: 'xS6B1l9V17I'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/M5Nwnu4O2vKrcLrMa72dFD9-Auo"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMjU0QjM3RTNFQzA0Q0ZCMw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Preludes, Op. 28, No. 4 in E Minor',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPreludes, Op. 28, No. 4 in E Minor · Frédéric Chopin · Claudio Arrau\n\nClassical Music Playlist\n\n℗ 2012 In The Mood\n\nReleased on: 2013-01-18\n\nMusic Publisher: WARNER CHAPPELL MUSIC INTERNATIONAL LTD\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/Hf2dJirHCm4/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/Hf2dJirHCm4/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/Hf2dJirHCm4/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/Hf2dJirHCm4/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/Hf2dJirHCm4/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 18,
            resourceId: {kind: 'youtube#video', videoId: 'Hf2dJirHCm4'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/Rew3tL01Bu3ShLuUnlc2NTfRV7U"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuOUJCRTAwOTFCRjgzRjJGNg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'William Tell Overture',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nWilliam Tell Overture · Various Artists · Gioachino Rossini · London Philharmonic Orchestra · Sir Thomas Beecham\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/DaRcAfHfE90/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/DaRcAfHfE90/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/DaRcAfHfE90/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/DaRcAfHfE90/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/DaRcAfHfE90/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 19,
            resourceId: {kind: 'youtube#video', videoId: 'DaRcAfHfE90'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/ecv-8jc4-_YmM1P2SOhwslZ-ovg"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQTc3OEE1MDUyNUI2OTYwOQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Suite bergamasque: III. Clair de lune',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nSuite bergamasque: III. Clair de lune · Claude Debussy · David Moore\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/YsHrHRd2k9M/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/YsHrHRd2k9M/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/YsHrHRd2k9M/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/YsHrHRd2k9M/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/YsHrHRd2k9M/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 20,
            resourceId: {kind: 'youtube#video', videoId: 'YsHrHRd2k9M'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/PQYksJAtk-mGeyRaAQW4iFg65zA"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNTRGREE1RDI5QTVFMjU1Ng==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Symphony No.1 in C minor, Op.68: II. Andante sostenuto',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nSymphony No.1 in C minor, Op.68: II. Andante sostenuto · Various Artists · Johannes Brahms · Italian Radio Symphony Orchestra · Sergiu Celibidache\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/6We3z7d35zM/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/6We3z7d35zM/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/6We3z7d35zM/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/6We3z7d35zM/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/6We3z7d35zM/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 21,
            resourceId: {kind: 'youtube#video', videoId: '6We3z7d35zM'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/glpDmFeMEc2x8dzmSR3aCKjEHug"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuRTVGN0E3RjVFNzY5RjI2Mw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'The Firebird',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nThe Firebird · Various Artists · Igor Stravinsky · London Philharmonic Orchestra · Ernest Ansermet\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/tngClcpQUtE/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/tngClcpQUtE/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/tngClcpQUtE/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/tngClcpQUtE/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/tngClcpQUtE/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 22,
            resourceId: {kind: 'youtube#video', videoId: 'tngClcpQUtE'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/ynCYwOX55K-l-rE8PiUyhCVfEGE"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuRDNEMjAxRjc0ODg5NzI4QQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Symphony No. 29 in A, K. 201: II. Andante',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nSymphony No. 29 in A, K. 201: II. Andante · Various Artists · Wolfgang Amadeus Mozart · Concertgebouw Orchestra · Eduard van Beinum\n\nClassical Music Playlist\n\n℗ 2012 In The Mood\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/MVoR_KUBcPE/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/MVoR_KUBcPE/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/MVoR_KUBcPE/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/MVoR_KUBcPE/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/MVoR_KUBcPE/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 23,
            resourceId: {kind: 'youtube#video', videoId: 'MVoR_KUBcPE'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/gB-ZWmzgfnUTbyiV8Oe_w3_sC6E"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMDc5MkVDRTUwREJDRDI4NA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Bolero',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nBolero · Various Artists · Maurice Ravel · Concertgebouw Orchestra · Eduard van Beinum\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/m7CVnxyKTr4/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/m7CVnxyKTr4/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/m7CVnxyKTr4/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/m7CVnxyKTr4/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/m7CVnxyKTr4/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 24,
            resourceId: {kind: 'youtube#video', videoId: 'm7CVnxyKTr4'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/B18TdVKx764jONgeqtCfoI-nvXg"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuRjRFMUY5NDUxNkQ4MjA5Nw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Romeo and Juliet, Op. 17: Part One - Introduction, Prologue, Stophes, Scherzetto',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nRomeo and Juliet, Op. 17: Part One - Introduction, Prologue, Stophes, Scherzetto · Hector Berlioz · London Symphony Orchestra · London Symphony Chorus · Pierre Monteux · Regina Resnik · Andre Turp · David Ward\n\nClassical Music Playlist\n\n℗ 2012 Saland Publishing\n\nReleased on: 2013-01-18\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/bdzbSA3WyzM/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/bdzbSA3WyzM/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/bdzbSA3WyzM/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/bdzbSA3WyzM/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/bdzbSA3WyzM/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 25,
            resourceId: {kind: 'youtube#video', videoId: 'bdzbSA3WyzM'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/1Elf9HEWtQRcUZldvpWPRb3JKwk"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNkZFNDQxOERCQkUzMUFEQw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Night on Bald Mountain',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nNight on Bald Mountain · Various Artists · Modest Mussorgsky · RIAS-Sinfonie-Orchester Berlin · Ferenc Fricsay\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Boosey and Hawkes\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/wKF0FT0l3FA/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/wKF0FT0l3FA/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/wKF0FT0l3FA/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/wKF0FT0l3FA/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/wKF0FT0l3FA/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 26,
            resourceId: {kind: 'youtube#video', videoId: 'wKF0FT0l3FA'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/PyyL5vFBRupx5BYQnAF8dU2aqZg"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNDNCNUNCQjhBRkVEODkwRQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'The Carnival of the Animals: XIII. The Swan',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nThe Carnival of the Animals: XIII. The Swan · Various Artists · Camille Saint-Saëns · Concerts Arts Orchestra · Felix Slatkin\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/t-o8YRMwt_g/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/t-o8YRMwt_g/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/t-o8YRMwt_g/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/t-o8YRMwt_g/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/t-o8YRMwt_g/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 27,
            resourceId: {kind: 'youtube#video', videoId: 't-o8YRMwt_g'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/75w4bf8Y0E9-YYeLsvZiQKShi-Y"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNzUxNDk5QUFFRjg3OUVBRA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Adagio in G minor for strings and organ',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nAdagio in G minor for strings and organ · Various Artists · Remo Giazotto · I MusicI\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/hNGG7ShrT-4/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/hNGG7ShrT-4/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/hNGG7ShrT-4/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/hNGG7ShrT-4/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/hNGG7ShrT-4/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 28,
            resourceId: {kind: 'youtube#video', videoId: 'hNGG7ShrT-4'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/pFRz5Sj6G_atwpG4L0wtz2i0GJE"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQ0FBQzRDN0E3NDBBRDQ3Qg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: "Serenade in G major, 'Eine kleine Nachtmusik', K. 525: II. Romanze Andante",
            description: "Provided to YouTube by The Orchard Enterprises\n\nSerenade in G major, 'Eine kleine Nachtmusik', K. 525: II. Romanze Andante · Various Artists · Wolfgang Amadeus Mozart · Berlin Philharmonic Orchestra · Herbert von Karajan\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.",
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/pXJLeq1TlTk/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/pXJLeq1TlTk/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/pXJLeq1TlTk/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/pXJLeq1TlTk/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/pXJLeq1TlTk/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 29,
            resourceId: {kind: 'youtube#video', videoId: 'pXJLeq1TlTk'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/YAa9VlwrzfyiJ5PQvwvk3claxQI"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMzlGQzY0MkY3OUQ4REM1NA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Concerto No. 10 in G minor, Op. 3: III. Largo',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nConcerto No. 10 in G minor, Op. 3: III. Largo · Francesco Manfredini · I Musici\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/5qy7wvHC-9M/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/5qy7wvHC-9M/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/5qy7wvHC-9M/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/5qy7wvHC-9M/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/5qy7wvHC-9M/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 30,
            resourceId: {kind: 'youtube#video', videoId: '5qy7wvHC-9M'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/_IbHKH2TOeDuKQVwt7PeYjPDT9k"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQjJDMTZGREJCNDNFOEQ1Qw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Die Walküre, Act III: The Ride of the Valkyries',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nDie Walküre, Act III: The Ride of the Valkyries · Various Artists · Richard Wagner · The Vienna Philharmonic Orchestra · Wilhelm Furtwängler\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: BMG RICORDI MUSIC PUBLISHING SPA\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/7wg1b7gW16M/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/7wg1b7gW16M/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/7wg1b7gW16M/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/7wg1b7gW16M/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/7wg1b7gW16M/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 31,
            resourceId: {kind: 'youtube#video', videoId: '7wg1b7gW16M'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/HSpeO2ItIZPQtNAo5P-hSuG-n04"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuRDE1NjAwQkRCRDBDNTAwOA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'The Planets, Op. 32: No. 2, Venus, the Bringer of Peace',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nThe Planets, Op. 32: No. 2, Venus, the Bringer of Peace · Various Artists · Gustav Holst · BBC Symphony Orchestra · Sir Malcolm Sargent\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/3ZXEQLFOwD8/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/3ZXEQLFOwD8/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/3ZXEQLFOwD8/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/3ZXEQLFOwD8/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/3ZXEQLFOwD8/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 32,
            resourceId: {kind: 'youtube#video', videoId: '3ZXEQLFOwD8'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/9XRKH3l4FQNeKbheYGVcQsUeELE"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuOTZCMTMyNjVDQkRFQzQ4OA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Pomp and Circumstance Marches, Op. 39: March No. 1 in D',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPomp and Circumstance Marches, Op. 39: March No. 1 in D · Various Artists · Edward Elgar · London Symphony Orchestra · Sir Malcolm Sargent\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/YNKf8_9VV8I/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/YNKf8_9VV8I/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/YNKf8_9VV8I/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/YNKf8_9VV8I/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/YNKf8_9VV8I/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 33,
            resourceId: {kind: 'youtube#video', videoId: 'YNKf8_9VV8I'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/mJeXluMDRxSxmB7Nf9Heh6w7UK8"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNkI5MUM5RjU2REU0RTg2RA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: "Rinaldo, HWV7: Act II, Lascia Ch'io Pianga",
            description: "Provided to YouTube by The Orchard Enterprises\n\nRinaldo, HWV7: Act II, Lascia Ch'io Pianga · George Frideric Handel · Ché & Charlie\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.",
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/oX77nwDyi3o/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/oX77nwDyi3o/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/oX77nwDyi3o/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/oX77nwDyi3o/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/oX77nwDyi3o/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 34,
            resourceId: {kind: 'youtube#video', videoId: 'oX77nwDyi3o'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/OEoQm3AErHokkhNvVRkERb4fQFE"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuOUY5ODE2MDZDNUU5OUEzRg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: "Prince of Denmark's March 'Trumpet Voluntary'",
            description: "Provided to YouTube by The Orchard Enterprises\n\nPrince of Denmark's March 'Trumpet Voluntary' · Various Artists · Jeremiah Clarke · The Unicorn Orchestra · Harry Ellis Dickson\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.",
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/OvqktcsEy34/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/OvqktcsEy34/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/OvqktcsEy34/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/OvqktcsEy34/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/OvqktcsEy34/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 35,
            resourceId: {kind: 'youtube#video', videoId: 'OvqktcsEy34'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/HTgcFz2Fvb0lK_YBmeHp7GAc_oo"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNUQ5OUFBMjdENzVFMDMzNQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Trumpet Tune And Air',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nTrumpet Tune And Air · Various Artists · Henry Purcell · Unicorn Orchestra · Harry Ellis Dickson\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/ENIttjWxwZk/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/ENIttjWxwZk/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/ENIttjWxwZk/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/ENIttjWxwZk/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/ENIttjWxwZk/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 36,
            resourceId: {kind: 'youtube#video', videoId: 'ENIttjWxwZk'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/PqzwBGH6XSMy2f0W4qERT09Ihw4"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNUEyOEU0QzYxRkYxM0JFQg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Symphony for Organ No. 5 in F Minor, Op. 42, No. 1: V. Toccata',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nSymphony for Organ No. 5 in F Minor, Op. 42, No. 1: V. Toccata · Charles-Marie Widor · Ralph Downes\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/Y-nxFybq0Js/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/Y-nxFybq0Js/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/Y-nxFybq0Js/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/Y-nxFybq0Js/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/Y-nxFybq0Js/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 37,
            resourceId: {kind: 'youtube#video', videoId: 'Y-nxFybq0Js'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/y5te4FadRwgs3pzFmrgAlhQBLyc"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuM0RFOUU5NkFDMzBEQzk3Qw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Swan Lake: Act I, No.2, Waltz - Tempo di valse',
            description: "Provided to YouTube by The Orchard Enterprises\n\nSwan Lake: Act I, No.2, Waltz - Tempo di valse · Various Artists · Pyotr Ilyich Tchaikovsky · L'Orchestre de la Suisse Romande · Ernest Ansermet\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.",
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/xFIRn8IuwLU/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/xFIRn8IuwLU/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/xFIRn8IuwLU/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/xFIRn8IuwLU/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/xFIRn8IuwLU/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 38,
            resourceId: {kind: 'youtube#video', videoId: 'xFIRn8IuwLU'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/DI7SUKtYm6HmAWo_lnOo6CvkraQ"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNTNCNTExN0RBMDZGRDAyMA==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: "Peer Gynt - Suite No. 1, Op. 46: III. Anitra's Dance",
            description: "Provided to YouTube by The Orchard Enterprises\n\nPeer Gynt - Suite No. 1, Op. 46: III. Anitra's Dance · Various Artists · Edvard Grieg · Moscow Radio Orchestra · Nikolai Golovanov\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.",
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/i-Cg_VJ7oaA/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/i-Cg_VJ7oaA/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/i-Cg_VJ7oaA/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/i-Cg_VJ7oaA/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/i-Cg_VJ7oaA/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 39,
            resourceId: {kind: 'youtube#video', videoId: 'i-Cg_VJ7oaA'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/JIlRmXBow5ao6TxIKRSPOTX58OM"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuOTc5REEyRDVBMjlBN0RBRg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Caro Mio Ben',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nCaro Mio Ben · Giuseppe Giordani · Ché & Charlie\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/q6JUgQmc7cs/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/q6JUgQmc7cs/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/q6JUgQmc7cs/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/q6JUgQmc7cs/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/q6JUgQmc7cs/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 40,
            resourceId: {kind: 'youtube#video', videoId: 'q6JUgQmc7cs'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/5__MCIwMJIW-SvuQNwMMUQS6fyU"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMEE1MjAyODEzQkJDNkZGRQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Gayaneh: Sabre Dance',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nGayaneh: Sabre Dance · Various Artists · Aram Khachaturian · Vienna Philharmonic Orchestra\n\nClassical Music Playlist\n\n℗ 2013 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/--sqN_nVdtk/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/--sqN_nVdtk/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/--sqN_nVdtk/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/--sqN_nVdtk/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/--sqN_nVdtk/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 41,
            resourceId: {kind: 'youtube#video', videoId: '--sqN_nVdtk'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/ViQTeYc6SsmlR3_CppVj9V6zKa4"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuN0VENDhDQ0VBRjYxMDU5Qw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Fantasia On A Theme By Thomas Tallis',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nFantasia On A Theme By Thomas Tallis · Various Artists · Ralph Vaughan Williams · Philharmonia Orchestra · Sir Malcolm Sargent\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: SCHIRMER G INC\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/PpYkmrUmeZo/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/PpYkmrUmeZo/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/PpYkmrUmeZo/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/PpYkmrUmeZo/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/PpYkmrUmeZo/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 42,
            resourceId: {kind: 'youtube#video', videoId: 'PpYkmrUmeZo'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/6pw0GkCFAjVgPwkQ_z1dOJh5O1g"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuNjU1NzFEMTBBNDUzMURBMg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Sicilienne',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nSicilienne · Gabriel Fauré · Martin Ruderman · Laurindo Almedida\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: SCHIRMER G INC\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/ALqRibb_0Ow/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/ALqRibb_0Ow/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/ALqRibb_0Ow/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/ALqRibb_0Ow/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/ALqRibb_0Ow/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 43,
            resourceId: {kind: 'youtube#video', videoId: 'ALqRibb_0Ow'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/y5di3ZvHeo9w4wG8ciagwNAaj8g"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMjZBOUFDRkE1Q0M3ODRGQQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'On Hearing The First Cuckoo in Spring',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nOn Hearing The First Cuckoo in Spring · Various Artists · Frederick Delius · The Royal Philharmonic Orchestra · Sir Thomas Beecham\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Boosey & Hawkes\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/IFxlQLajSrk/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/IFxlQLajSrk/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/IFxlQLajSrk/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/IFxlQLajSrk/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/IFxlQLajSrk/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 44,
            resourceId: {kind: 'youtube#video', videoId: 'IFxlQLajSrk'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/kG3IlIKjbkYfylsHDdWv0ODEGaY"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuRjc0NkNBM0QwNkQ1NDlFNw==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Toccata and Fugue in C major: II. Adagio',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nToccata and Fugue in C major: II. Adagio · Johann Sebastian Bach · Michael Schneider\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/XyDlLfrba6s/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/XyDlLfrba6s/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/XyDlLfrba6s/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/XyDlLfrba6s/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/XyDlLfrba6s/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 45,
            resourceId: {kind: 'youtube#video', videoId: 'XyDlLfrba6s'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/XVPoJHyrE8Q9IQ1ZCpJu38qTxDk"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuQUY2OTFBNUUzQUZEREMxQg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: '1812 Overture (Edit)',
            description: 'Provided to YouTube by The Orchard Enterprises\n\n1812 Overture · Various Artists · Pyotr Ilyich Tchaikovsky · London Philharmonic Orchestra · Sir Adrian Boult\n\nClassical Music Playlist\n\n℗ 2012 In The Mood\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/lZOdBQ60e5E/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/lZOdBQ60e5E/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/lZOdBQ60e5E/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/lZOdBQ60e5E/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/lZOdBQ60e5E/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 46,
            resourceId: {kind: 'youtube#video', videoId: 'lZOdBQ60e5E'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/3GQA4RI5tbD63oswK1HIj8YJ7Ko"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMkU1RTBBRDhBMUJBNjEwNg==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Ballades, Op. 10: No. 2 in D major. Andante',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nBallades, Op. 10: No. 2 in D major. Andante · Johannes Brahms · Wilhelm Kempff\n\nClassical Music Playlist\n\n℗ 2012 In The Mood\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/rxmF1SbWe9o/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/rxmF1SbWe9o/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/rxmF1SbWe9o/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/rxmF1SbWe9o/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/rxmF1SbWe9o/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 47,
            resourceId: {kind: 'youtube#video', videoId: 'rxmF1SbWe9o'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/ndLfFLZwcQn0gPTnDpwpPe_h0GE"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuMkU2QkUzNDVERTc4RTVGQQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Pomp and Circumstance Marches, Op. 39: March No. 4 in G',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nPomp and Circumstance Marches, Op. 39: March No. 4 in G · Various Artists · Edward Elgar · London Symphony Orchestra · Sir Malcolm Sargent\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/Wlnb2_ojyZo/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/Wlnb2_ojyZo/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/Wlnb2_ojyZo/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/Wlnb2_ojyZo/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/Wlnb2_ojyZo/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 48,
            resourceId: {kind: 'youtube#video', videoId: 'Wlnb2_ojyZo'}
        }
    }, {
        kind: 'youtube#playlistItem',
        etag: '"XI7nbFXulYBIpL0ayR_gDh3eu1k/nd47AP_2ZtorPcOWSFzeDJxjFY8"',
        id: 'T0xBSzV1eV9tdDFnVW5DYWhvZTJnNXJZT0NDeExVX3BNeEJ4Y1NiUHcuOTA4MjY2NjMzMDBBRkQyOQ==',
        snippet: {
            publishedAt: '2018-11-28T12:25:01.000Z',
            channelId: 'UCBR8-60-B28hp2BmDPdntcQ',
            title: 'Concerto for Double String Orchestra: I. Allegro con brio',
            description: 'Provided to YouTube by The Orchard Enterprises\n\nConcerto for Double String Orchestra: I. Allegro con brio · Various Artists · Michael Tippett · Philharmonia Orchestra · Walter Goehr\n\nClassical Music Playlist\n\n℗ 2012 Past Classics\n\nReleased on: 2013-01-18\n\nMusic Publisher: Saland Publishing\n\nAuto-generated by YouTube.',
            thumbnails: {
                default: {url: 'https://i.ytimg.com/vi/KuhDxEQzuPA/default.jpg', width: 120, height: 90},
                medium: {url: 'https://i.ytimg.com/vi/KuhDxEQzuPA/mqdefault.jpg', width: 320, height: 180},
                high: {url: 'https://i.ytimg.com/vi/KuhDxEQzuPA/hqdefault.jpg', width: 480, height: 360},
                standard: {url: 'https://i.ytimg.com/vi/KuhDxEQzuPA/sddefault.jpg', width: 640, height: 480},
                maxres: {url: 'https://i.ytimg.com/vi/KuhDxEQzuPA/maxresdefault.jpg', width: 1280, height: 720}
            },
            channelTitle: 'YouTube Spotlight',
            playlistId: 'OLAK5uy_mt1gUnCahoe2g5rYOCCxLU_pMxBxcSbPw',
            position: 49,
            resourceId: {kind: 'youtube#video', videoId: 'KuhDxEQzuPA'}
        }
    }]
};